/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface UrlHome {
    }
    interface UrlLoading {
        "name": string;
    }
    interface UrlProfile {
        "name": string;
    }
    interface UrlSettings {
        "name": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLUrlHomeElement extends Components.UrlHome, HTMLStencilElement {
    }
    var HTMLUrlHomeElement: {
        prototype: HTMLUrlHomeElement;
        new (): HTMLUrlHomeElement;
    };
    interface HTMLUrlLoadingElement extends Components.UrlLoading, HTMLStencilElement {
    }
    var HTMLUrlLoadingElement: {
        prototype: HTMLUrlLoadingElement;
        new (): HTMLUrlLoadingElement;
    };
    interface HTMLUrlProfileElement extends Components.UrlProfile, HTMLStencilElement {
    }
    var HTMLUrlProfileElement: {
        prototype: HTMLUrlProfileElement;
        new (): HTMLUrlProfileElement;
    };
    interface HTMLUrlSettingsElement extends Components.UrlSettings, HTMLStencilElement {
    }
    var HTMLUrlSettingsElement: {
        prototype: HTMLUrlSettingsElement;
        new (): HTMLUrlSettingsElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "url-home": HTMLUrlHomeElement;
        "url-loading": HTMLUrlLoadingElement;
        "url-profile": HTMLUrlProfileElement;
        "url-settings": HTMLUrlSettingsElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface UrlHome {
    }
    interface UrlLoading {
        "name"?: string;
    }
    interface UrlProfile {
        "name"?: string;
    }
    interface UrlSettings {
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "url-home": UrlHome;
        "url-loading": UrlLoading;
        "url-profile": UrlProfile;
        "url-settings": UrlSettings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "url-home": LocalJSX.UrlHome & JSXBase.HTMLAttributes<HTMLUrlHomeElement>;
            "url-loading": LocalJSX.UrlLoading & JSXBase.HTMLAttributes<HTMLUrlLoadingElement>;
            "url-profile": LocalJSX.UrlProfile & JSXBase.HTMLAttributes<HTMLUrlProfileElement>;
            "url-settings": LocalJSX.UrlSettings & JSXBase.HTMLAttributes<HTMLUrlSettingsElement>;
        }
    }
}
